TravelFun/TravelFun/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('food/', include('food_app.urls')),
    path('funstyle/', include('funstyle_app.urls')),
]

TravelFun/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('member_list/', views.member_list, name='member_list'),
    path('member/edit/<int:id>/', views.edit_member, name='edit_member'),  # 編輯會員
    path('member/delete/<int:id>/', views.delete_member, name='delete_member'),  # 刪除會員
    path('no_permission/', views.no_permission, name='no_permission'),
    path('add_member/', views.add_member, name='add_member'),
    path('search_members/', views.search_members, name='search_members')
    
]

TravelFun/travel_app/urls.py
from django.urls import path
from . import views
app_name='travel'
urlpatterns = [
    path('', views.travel_main, name='travel'),
    path('register/', views.register, name='register'),
   
    path('preview/<int:id>', views.preview, name='preview'),

    #資料crud
    path('register01/', views.register01, name='register01'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('edit01/<int:id>', views.edit01, name='edit01'),
    path('delete/<int:id>', views.delete, name='delete'),
  
    #顯示讀取資料
    path('region/', views.region, name='region'),
    path('town/<str:region_name>', views.town),
    path('show/<str:town_name>', views.show),
  

    #確認資料
    path('travelName/', views.travelName, name='travelName'),
    path('travelTel/', views.travelTel, name='travelTel'),
    path('travelAddress/', views.travelAddress, name='travelAddress'),
    path('travelRegion/', views.travelRegion, name='travelRegion'),
    path('travelTown/', views.travelTown, name='travelTown'),
]

TravelFun/travel_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Counties(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'counties'


class Taiwen(models.Model):
    taiwen_id = models.AutoField(primary_key=True)
    region = models.CharField(max_length=20)
    town = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'taiwen'


class Travel(models.Model):
    travel_id = models.AutoField(primary_key=True)
    travel_name = models.CharField(max_length=50)
    travel_txt = models.TextField(blank=True, null=True)
    tel = models.CharField(max_length=50, blank=True, null=True)
    travel_address = models.TextField()
    region = models.CharField(max_length=10)
    town = models.CharField(max_length=10)
    travel_linginfo = models.TextField(blank=True, null=True)
    opentime = models.TextField(blank=True, null=True)
    image1 = models.TextField(blank=True, null=True)
    image2 = models.TextField(blank=True, null=True)
    image3 = models.TextField(blank=True, null=True)
    px = models.DecimalField(db_column='Px', max_digits=12, decimal_places=8, blank=True, null=True)  # Field name made lowercase.
    py = models.DecimalField(db_column='Py', max_digits=12, decimal_places=8, blank=True, null=True)  # Field name made lowercase.
    class1 = models.ForeignKey('TravelClass', models.DO_NOTHING, db_column='class1')
    class2 = models.ForeignKey('TravelClass', models.DO_NOTHING, db_column='class2', related_name='travel_class2_set', blank=True, null=True)
    class3 = models.ForeignKey('TravelClass', models.DO_NOTHING, db_column='class3', related_name='travel_class3_set', blank=True, null=True)
    website = models.TextField(blank=True, null=True)
    ticketinfo = models.TextField(blank=True, null=True)
    parkinginfo = models.TextField(blank=True, null=True)
    upload = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'travel'


class TravelClass(models.Model):
    class_id = models.IntegerField(primary_key=True)
    class_name = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'travel_class'

TravelFun/travel_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, FileResponse
from .models import Travel,Taiwen,Counties,TravelClass
from datetime import datetime
import time
import json
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def travel_main(request):
    if request.method == 'POST':
        travelName = request.POST.get('name')
        if travelName:
            travel = Travel.objects.filter(travel_name__icontains=travelName)
            return render(request, 'travel/travel.html', {"travel":travel})

    travel = Travel.objects.all()
    return render(request, 'travel/travel.html', {"travel":travel})


def register(request):
    
    return render(request, 'travel/register.html')

def edit(request, id):   
    travel = Travel.objects.get(travel_id=id)  
    return render(request, 'travel/edit.html',{'travel': travel})

#新增資料
def register01(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        txt = request.POST.get('txt')
        tel = request.POST.get('tel')
        address = request.POST.get('address')
        region = request.POST.get("region")
        town = request.POST.get('town')
        linginfo = request.POST.get('linginfo')
        opentime = request.POST.get('opentime')
        image1 = request.POST.get('image1')
        image2 = request.POST.get('image2')
        image3 = request.POST.get('image3')
        Px = request.POST.get('Px')
        Py = request.POST.get('Py')
        website = request.POST.get('website')
        tickinfo = request.POST.get('tickinfo')
        parkinfo = request.POST.get('parkinfo')

        #景點屬性

        class_list = request.POST.getlist("class")
        if not class_list:
            return HttpResponse("您好，請至少選一個類別", 'text/plain')
        class1=class_list[0]
        if len(class_list)>=2:
            class2=class_list[1]
        else:
            class2=None
        if len(class_list)>=3:
            class3=class_list[2]
        else:
            class3=None
    #確認資料是否是NULL
    if not name:
       return HttpResponse("您好，景點名稱不能是空的", 'text/plain')
    if not Px or not Py :
        return HttpResponse("您好，經/緯度不能是空的", 'text/plain')
    if Travel.objects.filter(travel_name=name):
       return HttpResponse("您好，景點名稱已註冊", 'text/plain')
    if not region or not town:
        return HttpResponse("您好，縣市/鄉鎮市(區)欄位不能為空", 'text/plain')
    
    #確認資料是否存在
    if tel and Travel.objects.filter(tel=tel):
       return HttpResponse("您好，此電話已註冊", 'text/plain')
    if address and Travel.objects.filter(travel_address=address):
       return HttpResponse("您好，此地址已註冊", 'text/plain')
    if not Counties.objects.filter(name=region):
        return HttpResponse("您好，此縣市不存在", 'text/plain')
    if not Taiwen.objects.filter(region=region,town=town) :
        return HttpResponse("您好，這縣市，不存在此鄉鎮市", 'text/plain')
    
    
    # 把檔案寫進uploads資料夾
    uploaded_file = request.FILES.get('avator')
    if uploaded_file:
       fs = FileSystemStorage()
       file_name = fs.save(uploaded_file.name, uploaded_file)
    
    Travel.objects.create(
        travel_name = name,
        travel_txt = txt,
        tel = tel,
        travel_address = address,
        region = region,
        town = town,
        travel_linginfo =linginfo,
        opentime = opentime,
        image1 = image1,
        image2 = image2,
        image3 = image3,
        px = Px,
        py = Py,
        class1_id = class1,
        class2_id = class2,
        class3_id = class3,
        website = website,
        ticketinfo = tickinfo,
        parkinginfo = parkinfo,
        upload = datetime.now()
    )
    content =  f"您好，景點:{name}，已加入資料庫  "
    return HttpResponse(content, 'text/plain')

def edit01(request,id):
    travel = Travel.objects.get(travel_id=id) 
    if request.method == 'POST':
        #輸入名字
        if travel.travel_name != request.POST.get('name'):
            if Travel.objects.filter(travel_name=request.POST.get('name')):
                return HttpResponse("您好，景點名稱已註冊", 'text/plain')
            else:
                travel.travel_name = request.POST.get('name')
        
        travel.travel_txt = request.POST.get('txt')
        #輸入電話
        if travel.tel != request.POST.get('tel'):
            if travel.tel and Travel.objects.filter(tel=travel.tel):
                return HttpResponse("您好，此電話已註冊", 'text/plain')
            else :
                travel.tel = request.POST.get('tel')

        #輸入地址
        if travel.travel_address != request.POST.get('address'):
            if travel.travel_address and Travel.objects.filter(travel_address=travel.travel_address):
                return HttpResponse("您好，此地址已註冊", 'text/plain')
            else :
                travel.travel_address = request.POST.get('address')
        travel.region = request.POST.get("region")
        travel.town = request.POST.get('town')
        travel.travel_linginfo = request.POST.get('linginfo')
        travel.opentime = request.POST.get('opentime')
        travel.image1 = request.POST.get('image1')
        travel.image2 = request.POST.get('image2')
        travel.image3 = request.POST.get('image3')
        travel.px = request.POST.get('Px')
        travel.py = request.POST.get('Py')
        travel.website = request.POST.get('website')
        travel.ticketinfo = request.POST.get('tickinfo')
        travel.parkinginfo = request.POST.get('parkinfo')

        #景點屬性
        if not request.POST.getlist("class"):
            return HttpResponse("您好，請至少選一個類別", 'text/plain')
        class1 = TravelClass.objects.get(class_id=request.POST.getlist("class")[0])
        travel.class1=class1
        if len(request.POST.getlist("class"))>=2:
            class2 = TravelClass.objects.get(class_id=request.POST.getlist("class")[1])
            travel.class2=class2
        if len(request.POST.getlist("class"))>=3:
            class3 = TravelClass.objects.get(class_id=request.POST.getlist("class")[2])
            travel.class3=class3

    #確認資料是否是NULL
    if not travel.travel_name:
       return HttpResponse("您好，景點名稱不能是空的", 'text/plain')
    if not travel.px or not travel.py :
        return HttpResponse("您好，經/緯度不能是空的", 'text/plain')
    if not travel.region or not travel.town:
        return HttpResponse("您好，縣市/鄉鎮市(區)欄位不能為空", 'text/plain')
    
    #確認資料是否存在
    
    if not Counties.objects.filter(name=travel.region):
        return HttpResponse("您好，此縣市不存在", 'text/plain')
    if not Taiwen.objects.filter(region=travel.region,town=travel.town) :
        return HttpResponse("您好，這縣市，不存在此鄉鎮市", 'text/plain')
    
    
    # 把檔案寫進uploads資料夾
    uploaded_file1 = request.FILES.get('image1')
    uploaded_file2 = request.FILES.get('image2')
    uploaded_file3 = request.FILES.get('image3')

    if uploaded_file1:
       fs = FileSystemStorage()
       travel.image1 = fs.save(uploaded_file1.name, uploaded_file1)
    if uploaded_file2:
       fs = FileSystemStorage()
       travel.image2 = fs.save(uploaded_file2.name, uploaded_file2)
    if uploaded_file3:
       fs = FileSystemStorage()
       travel.image3 = fs.save(uploaded_file3.name, uploaded_file3)

    travel.save()
    content =  f"您好，景點資訊，已修改  "
    return HttpResponse(content, 'text/plain')
    


#刪除資料
def delete(request, id):   
    todo = Travel.objects.get(travel_id=id)  
    todo.delete()
    return redirect('travel:travel')

#預覽資料
def preview(request,id):
    travel = Travel.objects.get(travel_id=id) 
    classes = TravelClass.objects.all()

    return render(request,"travel/preview.html",{'travel': travel})


#讀取縣市資料
def region(request):
    regions = Counties.objects.values('name').distinct()
    regions = [item['name'] for item in regions]
    return JsonResponse(regions, safe=False)

#讀取鄉鎮市區資料
def town(request, region_name): 
    towns = Taiwen.objects.filter(region=region_name).values('town')
    towns = [item['town'] for item in towns]
    return JsonResponse(towns, safe=False)

#顯示篩選資料
def show(request, town_name):
    travels = Travel.objects.filter(town = town_name).values()
    print(travels)
    travels = [item for item in travels]
    print(travels)
    return JsonResponse(travels, safe=False)

#確認景點名稱
def travelName(request):
    name = request.GET.get("name")
    result = {
        "name_exists": False,
    }
    if Travel.objects.filter(travel_name=name).exists():
        result["name_exists"] = True
    return JsonResponse(result, safe=False)

#確認電話
def travelTel(request):
    tel = request.GET.get("tel")
    result = {
        "tel_exists": False,
    }
    if Travel.objects.filter(tel=tel).exists():
        result["tel_exists"] = True
    return JsonResponse(result, safe=False)

#確認地址
def travelAddress(request):
    address = request.GET.get("address")
    result = {
        "address_exists": False,
    }
    if Travel.objects.filter(travel_address=address).exists():
        result["address_exists"] = True
    return JsonResponse(result, safe=False)

#確認縣市
def travelRegion(request):
    region = request.GET.get("region")
    result = {
        "region_exists": False,
    }
    if Counties.objects.filter(name=region).exists():
        result["regoin_exists"] = False
    return JsonResponse(result, safe=True)

#確認鄉鎮市區
def travelTown(request):
    town = request.GET.get("town")
    result = {
        "town_exists": False,
    }
    if Taiwen.objects.filter(town=town).exists():
        result["town_exists"] = False
    return JsonResponse(result, safe=False)

TravelFun/travel_app/templates/travel/edit.html
{% block styles %}
<style>

</style>
{% endblock %}
{% block content %}
<form id="registerForm" method="POST" enctype="multipart/form-data">  
  {% csrf_token %}
  <div class="mb-3">
   <label for="InputName" class="form-label">景點名稱</label>
   <input type="text" class="form-control" id="InputName" name="name" value="{{travel.travel_name}}">
   <div id="nameHelp" class="form-text"></div>
 </div>
   <div class="mb-3">
     <label for="InputTxt" class="form-label">景點介紹</label>
     <textarea style="height:50px;" type="text" class="form-control" id="InputTxt" name="txt">{{travel.travel_txt}} </textarea>
     <div id="divTxt" class="form-text"></div>
   </div>
   <div class="mb-3">
    <label for="InputTel" class="form-label">電話資訊</label>
    <input type="tel" class="form-control" id="Inputtel" name="tel" value="{{travel.tel}}">
    <div id="divTel" class="form-text"></div>
  </div>
  <div class="mb-3">
    <label for="InputAddress" class="form-label">景點地址</label>
    <input type="text" class="form-control" id="InputAddress" name="address" value="{{travel.travel_address}}">
    <div id="divAddress" class="form-text"></div>
  </div>
   <div class="mb-3">
     <label for="InputRegion" class="form-label">縣/市</label>
     <input type="region" class="form-control" id="InputRegion" name="region" value="{{travel.region}}">
     <div id="divRegion" class="form-text"></div>
   </div>
   <div class="mb-3">
    <label for="InputTown" class="form-label">鄉/鎮/市/區</label>
    <input type="town" class="form-control" id="InputTown" name="town" value="{{travel.town}}">
    <div id="divTown" class="form-text"></div>
  </div>
   <div class="mb-3">
    <label for="formFile1" class="form-label">圖片1</label>
    <input class="form-control" type="file" id="formFile1" name="image1" value="{{travel.travel_name}}">
  </div>
  <div class="mb-3">
    <label for="formFile2" class="form-label">圖片2</label>
    <input class="form-contro2" type="file" id="formFile2" name="image2" value="{{travel.travel_name}}">
  </div>
  <div class="mb-3">
    <label for="formFile3" class="form-label">圖片3</label>
    <input class="form-control" type="file" id="formFile3" name="image3" value="{{travel.travel_name}}">
  </div>
  <div class="mb-3">
    <label for="InputLinginfo" class="form-label">交通</label>
    <input type="text" class="form-control" id="Linginfo" name="linginfo" value="{{travel.travel_ligininfo}}">
  </div>
  <div class="mb-3">
    <label for="InputOpentime" class="form-label">營業時間</label>
    <input type="text" class="form-control" id="InputOpentime" name="opentime" value="{{travel.opentime}}">
  </div>
  <div class="mb-3">
    <h7>經度/緯度(範例:41.40338, 2.17403 小數點只到第五位)</h7>
    <label for="InputPx" class="form-label">經度:</label>
    <input type="number" step='0.00001' class="form-control" id="InputPx" name="Px" value="{{travel.px}}">
    <label for="InputPy" class="form-label">緯度:</label>
    <input type="number" step='0.00001' class="form-control" id="InputPy" name="Py" value="{{travel.py}}">
    <div id="divpxy" class="form-text"></div>
  </div>
  <div class="mb-3">
    <label for="InputWbsite" class="form-label">網站資訊</label>
    <input type="text" class="form-control" id="InputWebsite" name="website" value="{{travel.website}}">
  </div>
  <div class="mb-3">
    <label for="InputTicketinfo" class="form-label">票價</label>
    <input type="text" class="form-control" id="InputTicketinfoe" name="ticketinfo" value="{{travel.ticketinfo}}">
  </div>
  <div class="mb-3">
    <label for="InputParkinginfo" class="form-label">附近停車場</label>
    <input type="text" class="form-control" id="InputParkinginfo" name="parkinginfo" value="{{travel.parkinginfo}}">
    <div id="nameHelp" class="form-text"></div>
  </div>
  <div>
    <label for="InputParkinginfo" class="form-label">景點屬性:</label>
    <label>
      <input type="checkbox" name="class" value="1" onclick="return checkCount(this)" >文化類
    </label>
    <label>
      <input type="checkbox" name="class" value="2" onclick="return checkCount(this)">生態類
    </label>
    <label>
      <input type="checkbox" name="class" value="3" onclick="return checkCount(this)">古蹟類
    </label>
    <label>
      <input type="checkbox" name="class" value="4" onclick="return checkCount(this)">廟宇類
    </label>
    <label><input type="checkbox" name="class" value="5" onclick="return checkCount(this)">藝術類
    </label>
    <label><input type="checkbox" name="class" value="6" onclick="return checkCount(this)">小吃/特產類
    </label>
    <label><input type="checkbox" name="class" value="7" onclick="return checkCount(this)">國家公園類
    </label>
    <label>
      <input type="checkbox" name="class" value="8" onclick="return checkCount(this)">國家風景區類
    </label>
    <label>
      <input type="checkbox" name="class" value="9" onclick="return checkCount(this)">休閒農業類
    </label>
    <label>
      <input type="checkbox" name="class" value="10" onclick="return checkCount(this)" >溫泉類
    </label>
    <label>
      <input type="checkbox" name="class" value="11" onclick="return checkCount(this)">自然風景類
    </label>
    <label>
      <input type="checkbox" name="class" value="12" onclick="return checkCount(this)">遊憩類
    </label>
    <label>
      <input type="checkbox" name="class" value="13" onclick="return checkCount(this)">體育健身類
    </label>
    <label>
      <input type="checkbox" name="class" value="14" onclick="return checkCount(this)">觀光工廠類
    </label>
    <label>
      <input type="checkbox" name="class" value="15" onclick="return checkCount(this)">都會公園類
    </label>
    <label>
      <input type="checkbox" name="class" value="16" onclick="return checkCount(this)">森林遊樂區類
    </label>
    <label>
      <input type="checkbox" name="class" value="17" onclick="return checkCount(this)">林場類
    </label>
    <label>
      <input type="checkbox" name="class" value="18" onclick="return checkCount(this)">
      其他
    </label>

  </div>
  
   <button type="submit" class="btn btn-primary" id="buttonSubmit">送出</button>
   
 </form>
 <div id="div1" class="alert alert-info mt-3"></div>
 <a href="/travel/" class="btn btn-danger" >回首頁</a>
{% endblock %}
{% block scripts %}
<script>

  var checkedCount = 0;
  function checkCount(obj) {
    if (obj.checked === true) {
        if (checkedCount >= 3) {
            alert("最多只能選3項喔");
            return false;
        }
        checkedCount++;
    }
    else {
        checkedCount--;
    }

    return true
  }
  function toVaild() {
    if (checkedCount == 0) {
        alert("請至少選澤一種類型");
        return false;
    }
    return true;
  }
  
  const inpName = document.querySelector('#InputName')
  const divName = document.querySelector('#nameHelp')
  inpName.addEventListener("blur", async ()=>{  
        const response = await fetch(`/travel/travelName/?name=${inpName.value}`)
        const nameInfo = await response.json()
        if (nameInfo.name_exists){
          divName.innerText= '景點名稱已存在'
        }
        else {
          divName.innerText =''
        }

        divName.innerHTML= divName.innerText
    })

   const inpTxt = document.querySelector('#InputTxt')

    const inpTel = document.querySelector('#InputTel')
    const divTel = document.querySelector('#divtel')
    inpTel.addEventListener("blur", async ()=>{
        const response = await fetch(`/travel/trevelTel/?tel=${inpTel.value}`)
        const telInfo = await response.json()

        if (telInfo.tel_exists){
            divTel.innerText= '電話已註冊';
        }
        else {
            divTel.innerText ='';
        }

        divTel.innerHTML= divTel.innerText
    })
    

    const inpAddress = document.querySelector('#InputAddress')
    const divAddress = document.querySelector('#divAddress')
    inpAddress.addEventListener("blur", async()=>{
      const response = await fetch(`/travel/travelAddress/?address=${inpAddress.value}`)
      const addressInfo = await response.json()
      if (addressInfo.tel_exists){
        divAddress.innerText= '地址已註冊';
      }
      else {
        divAddress.innerText ='';
      }

      divAddress.innerHTML= divAddress.innerText
    })

    const inputRegion = document.querySelector('#InputRegion')
    const divRegion = document.querySelector('#divRegion')
    inputRegion.addEventListener("blur", async()=>{
      const response = await fetch(`/travel/travelRegion/?Region=${inputRegion.value}`)
      const regionInfo = await response.json()
      if (regionInfo.region_exists){
        divRegion.innerText= '縣市不存在';
      }
      else {
        divRegion.innerText ='';
      }
      divRegion.innerHTML= divRegion.innerText
    })

    const inputTown = document.querySelector('#InputTown')
    const divTown = document.querySelector('#divAddress')
    inputTown.addEventListener("blur", async()=>{
      const response = await fetch(`/travel/travelTown/?town=${inputTown.value}`)
      const townInfo = await response.json()
      if (townInfo.tel_exists){
        divTown.innerText= '鄉鎮市區不存在';
      }
      else {
        divTown.innerText ='';
      }

      divTown.innerHTML= divTown.innerText
    })


  const divInfo = document.querySelector('#div1')
  const btnSubmit = document.querySelector('#buttonSubmit')
   btnSubmit.addEventListener('click',async (event)=>{
      event.preventDefault()

      const myForm = document.querySelector('#registerForm')
      const formData = new FormData(myForm)

      const response = await fetch(`/travel/edit01/{{travel.travel_id}}`,{
        method:'POST',
        body:formData,
        headers:{
          'X-CSRFToken':'{{ csrf_token }}'
        }
      })
      const data = await response.text()
      divInfo.innerHTML = data 

   })


</script>

{% endblock %}

TravelFun/travel_app/templates/travel/travel.html
{% block styles %}
<style>

</style>
{% endblock %}
{% block content %}
<div style=" margin-bottom:10px">
    <h3>景點搜尋(選擇地址或直接搜尋名稱)</h3>
    <select id="selectRegion">
        <option value="0">請選擇</option>
    </select>
    <select id="selectTown"></select>
    <form  method="POST" enctype="multipart/form-data">  
        {% csrf_token %}
        <div class="mb-3">
         <label for="InputName" class="form-label">景點名稱</label>
         <input type="text" class="form-control" id="InputName" name="name">
         <button type="submit" class="btn btn-primary" id="buttonSubmit">搜尋ˋ</button>
</div>
<a style="margin-right:200 PX ;" href="{% url 'travel:register' %}" class="btn btn-danger" >新增</a>

<a href="/travel/" class="btn btn-danger" >回首頁</a>

<div style="margin-top:10px">
    <table  class="table table-bordered">
        <thead>
            <tr>
                <th>景點</th>
                <th>類別</th>
                <th>電話</th>
                <th>縣市</th>
                <th>鄉鎮市(區)</th>
                <th>編輯</th>
            </tr>
        </thead>
            
        <tbody id="table">
            {% for item in travel %}
            <tr>
                <td>{{ item.travel_name }}</td>
                <td>{{ item.class1_id }}</td>
                <td>{{ item.tel }}</td>
                <td>{{ item.region}}</td>
                <td>{{ item.town}}</td>
                <td>
                    <a href="/travel/preview/{{item.travel_id}}" class="btn btn-danger" >預覽</a>
                    <a href="/travel/edit/{{item.travel_id}}" class="btn btn-danger" >修改</a>
                    <a href="/travel/delete/{{item.travel_id}}" class="btn btn-danger" >刪除</a>     
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <div id="div1"></div>
        
</div>

{% endblock %}
{% block scripts %}
<script>
 const selRegion = document.querySelector('#selectRegion');
 const selTown = document.querySelector('#selectTown');
 const divInfo = document.querySelector('#div1')
 const eleTable = document.querySelector('#table');
 (async ()=>{
    //call api 取得 JSON 資料
   const response = await fetch('/travel/region/')
   const regions = await response.json()
   const optsArray = regions.map((region,index) => `<option value="${region}">${index}-${region}</option>`)  
    //將資料顯示在網頁上
    selRegion.innerHTML = optsArray.join("")

    loadTown()
 })();

//根據城市名稱讀取鄉鎮區的資料
 const loadTown = async ()=>{
    const response = await fetch(`/travel/town/${selRegion.value}`)
    const towns = await response.json()

    const optsArray = towns.map((item)=>`<option value="${item}">${item}</option>`)

   selTown.innerHTML = optsArray.join("")

 }
 
 selRegion.addEventListener('change',()=>{
    loadTown()

 })

 selTown.addEventListener('change',async()=>{
    eleTable.innerHTML=""
    const response = await fetch(`/travel/show/${selTown.value}`)
    const towns = await response.json()
    console.log(towns)
    towns.forEach(item =>{
        if(item){
            let trip = `<tr>
                <td>${item.travel_name}</td>
                <td>${item.class1_id}</td>
                <td>${item.tel}</td>
                <td>${item.region}</td>
                <td>${item.town}</td>
                <td>
                    <a href="/travel/preview/${item.travel_id}" class="btn btn-danger" >預覽</a>
                    <a href="/travel/edit/${item.travel_id}" class="btn btn-danger" >修改</a>
                    <a href="/travel/delete/${item.travel_id}" class="btn btn-danger" >刪除</a>     
                </td>
                </tr>`;
                eleTable.innerHTML = eleTable.innerHTML+trip;
            }
    })  
})

</script>
{% endblock %}